"""
Layer 1 — Heuristics Classifier
"""

import re
import logging

logger = logging.getLogger(__name__)

MUSIC_KEYWORDS = {
    "official music video",
    "official audio",
    "official lyric video",
    "music video",
    "lyric video",
    "lyrics video",
    "official visualizer",
    "visualizer",
    "provided to youtube by",
    "auto-generated by youtube",
    "vevo",
    "topic",
    "lyrics"
}

NON_MUSIC_KEYWORDS = {
    "tutorial",
    "how to",
    "guide",
    "course",
    "lecture",
    "lesson",
    "explained",
    "step by step",
    "review",
    "unboxing",
    "comparison",
    "hands on",
    "first impressions",
    "gameplay",
    "walkthrough",
    "playthrough",
    "speedrun",
    "lets play",
    "podcast",
    "interview",
    "webinar",
    "conference",
    "ted talk",
    "discussion",
    "panel discussion",
    "news",
    "breaking news",
    "analysis",
    "documentary",
    "report",
    "highlights",
    "full match",
    "match highlights",
    "post match",
    "coding",
    "programming",
    "software",
    "ai tutorial",
    "vlog",
    "travel vlog",
    "daily vlog",
    "challenge",
    "prank",
    "reaction",
    "reaction video"
}

MUSIC_CHANNELS = {
    "vevo",
    "topic",
    "sony music",
    "sony music india",
    "sony music entertainment",
    "t-series",
    "zee music company",
    "saregama",
    "tips official",
    "lahari music",
    "aditya music",
    "think music india",
    "speed records",
    "desi music factory",
    "yrf",
    "yash raj films",
    "zee music",
    "warner music",
    "warner records",
    "universal music",
    "universal music india",
    "republic records",
    "atlantic records",
    "columbia records",
    "def jam",
    "interscope",
    "emi music",
    "capitol records",
    "spinnin records",
    "monstercat",
    "ncs",
    "no copyright sounds",
    "ultra records",
    "trap nation",
    "mrsuicidesheep",
    "cloudkid",
    "proximity",
    "armada music",
    "anjunabeats"
}

NON_MUSIC_CHANNELS = {
    "cnn",
    "bbc",
    "bbc news",
    "cnbc",
    "fox news",
    "al jazeera",
    "reuters",
    "nytimes",
    "the verge",
    "techcrunch",
    "mkbhd",
    "linus tech tips",
    "mrwhosetheboss",
    "vsauce",
    "veritasium",
    "kurzgesagt",
    "ted",
    "tedx talks",
    "freecodecamp",
    "fireship",
    "codewithharry",
    "cs50",
    "national geographic",
    "discovery",
    "history channel",
    "espn",
    "fifa",
    "nba",
    "mrbeast",
    "dude perfect"
}

def _normalize(text: str) -> str:
    return text.lower().strip() if text else ""


def classify(raw_title: str, channel: str) -> tuple[bool | None, str]:
    """
    Returns (is_music, classification_source_label) or (None, "") if unsure.
    """
    title_lower = _normalize(raw_title)
    channel_lower = _normalize(channel)

    # --- Channel-level signals (strongest) ---
    for kw in MUSIC_CHANNELS:
        if kw in channel_lower:
            logger.debug(f"L1 hit: music channel '{kw}'")
            return True, "layer1"

    for kw in NON_MUSIC_CHANNELS:
        if kw in channel_lower:
            logger.debug(f"L1 hit: non-music channel '{kw}'")
            return False, "layer1"

    # --- Title-level music signals ---
    music_hits = sum(1 for kw in MUSIC_KEYWORDS if kw in title_lower)
    non_music_hits = sum(1 for kw in NON_MUSIC_KEYWORDS if kw in title_lower)

    if music_hits >= 1 and non_music_hits == 0:
        return True, "layer1"

    if non_music_hits >= 1 and music_hits == 0:
        return False, "layer1"

    # --- Unsure ---
    logger.debug(f"L1 unsure for title='{raw_title}' channel='{channel}'")
    return None, ""
